language: rust
env:
  global:
    - PROJECT_NAME: imdb-rename
    - RUST_BACKTRACE: full
addons:
  apt:
    packages:
      - musl-tools
matrix:
  fast_finish: true
  include:
    # Nightly channel.
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    # Beta channel. We enable these to make sure there are no regressions in
    # Rust beta releases.
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    # Minimum Rust supported channel. We enable these to make sure imdb-rename
    # continues to work on the advertised minimum Rust version.
    - os: linux
      rust: 1.22.1
      env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  file_glob: true
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    branch: master
    tags: true
  api_key:
    - secure: WGgDfCcpwh39F2OjRl8TASuBSyfNsm4tnNjIO1mZXt6oB+cBMysFhgP9KpWHWmdeOD/iwjvLoPRz67QSWR14tP8roI13XH/R61wnHHSR6IiiHlpbrbZbyhz0UPXaDbK7NKAf8XKUuhsP2i0rgqbD6Zi/OAdV0msD9QJwcRq5mtm0FHMzOEfHKLNVXRoA//VTZN8XAA2JiyWTKGQnj4FG8kfbVmbgt6WYAdPTSKZsCLelaSEqu+jpTNAnDXc/Qz/phX8ejmxktIBB+N/PLBiZRRERUaR1rZsMVNKpQPx28P8OBT2C7csDeZDoSOaK1CTZuwhM7COC6Bd2NRKN869kRKcqGlYkjV7ZJ80x57q2dhGWSPCFEI3Ip+zq6m0vmqRG0KBisxknstDCFbsBjRzaI+3DKhAXqihi8+g3KvSWz/9Yxtn7+nNHchQYTC33MyjU5yigE3t+eRl23HqpTIIv3GwJ4JCyJIhrkEw9NRXBpD2upQ9rY9yXARu+JHypphqGjFe2FnVsYHagXh+KpsXUx/yUFh+yQWZKZLXOutyP/w+2kc/K1Ugzq5HFn8FYZxMsH1mR/OW1CMHK4m750LEDYMgBpGk+DuRkvwPGmNaV9pqH5RwD/vZtw79nKk1F0AoKii2FEijAtOAoVudavYqDNEPI7R76Rm7iwjgBzK/Tf98=
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed.
    - /^\d+\.\d+\.\d+.*$/
notifications:
  email:
    on_success: never
